version: '2'
services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: on-failure
    hostname: mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_USER=root1
      - MYSQL_PASSWORD=123123
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=tm
  spring:
    image: tm:latest
    hostname: spring
    restart: on-failure
    ports: 
      - 8080:8080
    depends_on: 
      - mysql
